### ISSUE TITLE
Проблема при работе на сервере

### ISSUE THREAD

**Issue by AlxVasilchenko** [sivakov512/yandex-geocoder#19]
На ПК работает, деплою тот же код на сервер и получаю ошибку:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/virtwww/w_jesuppv-rf_9d8d3c3c/django-env/lib/python3.9/site-packages/yandex_geocoder/client.py", line 48, in coordinates
    data = self._request(address)["GeoObjectCollection"]["featureMember"]
  File "/home/virtwww/w_jesuppv-rf_9d8d3c3c/django-env/lib/python3.9/site-packages/yandex_geocoder/client.py", line 40, in _request
    raise InvalidKey()
yandex_geocoder.exceptions.InvalidKey

**Comment by sivakov512** [comment]
Похоже, что используется неверный ключ
